spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager
    password:
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      continue-on-error: false
