# DataSource Configuration
spring.datasource.url=jdbc:mysql://192.168.1.216:3306/manager
spring.datasource.username=root
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8InnoDBDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization Configuration
spring.sql.init.mode=always
#app config
spring.application.name=Stage
spring.sql.init.continue-on-error=false
spring.datasource.hikari.connection-timeout=30000